test_name: When request is made, GET /studyfields/id returns 200 and a json body that matches created studyfield

marks:
  - parametrize:
      key:
        - request_code
        - request_name
      vals:
        - [ "CS101","computer_science" ]

stages:
  - &auth_save_token
    name: Login and save access token
    request:
      url: "{tavern.env_vars.AUTH_URL}/auth/login"
      method: POST
      headers:
        Content-Type: "application/json"
      json:
        email: "{tavern.env_vars.ADMIN_EMAIL:}"
        password: "{tavern.env_vars.ADMIN_PASSWORD}"
    response:
      status_code: 200
      json:
        access_token: !anystr
      save:
        json:
          returned_access_token: access_token
            
  - &create_studyfield_save_all
    name: "When request with valid json body, POST /studyfields returns 201"
    request:
      url: "{tavern.env_vars.BASE_URL}/studyfields"
      method: POST
      headers:
        Authorization: "Bearer {returned_access_token}"
        Content-Type: "application/json"
      json:
        code: "{request_code}"
        name: "{request_name}"
    response:
      status_code: 201
      json:
        id: !anyint
        code: "{request_code}"
        name: "{request_name}"
      save:
        json:
          returned_id: id
          returned_code: code
          returned_name: name

  - name: "When request is made,
            GET /studyfields/id returns 200 and a json body that matches created studyfield"
    request:
      url: "{tavern.env_vars.BASE_URL}/studyfields/{returned_id}"
      method: GET
      headers:
        Authorization: "Bearer {returned_access_token}"
    response:
      status_code: 200
      json:
        id: !int "{returned_id:d}"
        code: "{returned_code}"
        name: "{returned_name}"


finally:
  - &delete_studyfield
    name: "When study field exists, DELETE /studyfields/id returns 204"
    request:
      url: "{tavern.env_vars.BASE_URL}/studyfields/{returned_id}"
      method: DELETE
      headers:
        Authorization: "Bearer {returned_access_token}"
    response:
      status_code: 204

  - &delete_studyfield_check
    name: "When study field deleted, GET /studyfields/id returns 404"
    request:
      url: "{tavern.env_vars.BASE_URL}/studyfields/{returned_id}"
      method: GET
      headers:
        Authorization: "Bearer {returned_access_token}"
    response:
      status_code: 404

--- 

test_name: When request is made with extra parameters, GET /studyfields/id returns 400

marks:
  - parametrize:
      key:
        - request_code
        - request_name
        - request_extra_parameter
      vals:
        - [ "CS101","computer_science", "extra_info"]

stages:
  - *auth_save_token

  - &create_studyfield_save_id
    name: "When a request with a valid json body,
              POST /studyfields/id returns 201 and a json body that matches the request"
    request:
      url: "{tavern.env_vars.BASE_URL}/studyfields"
      method: POST
      headers:
        Authorization: "Bearer {returned_access_token}"
        Content-Type: "application/json"
      json:
        code: "{request_code}"
        name: "{request_name}"
    response:
      status_code: 201
      json:
        id: !anyint
        code: "{request_code}"
        name: "{request_name}"
      save:
        json:
          returned_id: id

  - name: "When request is made with extra parameters, GET /studyfields/id returns 400"
    request:
      url: "{tavern.env_vars.BASE_URL}/studyfields/{returned_id}"
      method: GET
      headers:
        Authorization: "Bearer {returned_access_token}"
      json:
        extra_parameter: "{request_extra_parameter}"
    response:
      status_code: 400

finally:
  - *delete_studyfield

  - *delete_studyfield_check

---

test_name: When request with invalid security key header, GET /studyfields/id returns 401

marks:
  - parametrize:
      key:
        - wrong_token
        - request_code
        - request_name
      vals:
        - [ "satsgag", "CS101","computer_science" ]

stages:
  - *auth_save_token

  - *create_studyfield_save_id

  - name: "When request with invalid security key header, GET /studyfields/id returns 401"
    request:
      url: "{tavern.env_vars.BASE_URL}/studyfields/{returned_id}"
      method: GET
      headers:
        Authorization: "Bearer {wrong_token}"
    response:
      status_code: 401

finally:
  - *delete_studyfield

  - *delete_studyfield_check
  
---

test_name: When studyfield deleted, GET /studyfields/id returns 404

marks:
  - parametrize:
      key:
        - request_code
        - request_name
      vals:
        - [ "CS101","computer_science" ]

stages:
  - *auth_save_token

  - *create_studyfield_save_id

finally:
  - *delete_studyfield

  - *delete_studyfield_check

---

test_name: When id from studyfield that not exist, GET /studyfields/id returns 404

marks:
  - parametrize:
      key:
        - wrong_id
      vals:
        - [ -1 ]

stages:
  - *auth_save_token

  - name: "When id from studyfield that not exist, GET /studyfields/id returns 404"
    request:
      url: "{tavern.env_vars.BASE_URL}/studyfields/{wrong_id}"
      method: GET
      headers:
        Authorization: "Bearer {returned_access_token}"
    response:
      status_code: 404

---

test_name:  When a request with a valid json body, PUT /studyfields/id returns 200 and a json body that matches request

marks:
  - parametrize:
      key:
        - request_code
        - request_name
        - update_code
        - update_name
      vals:
        - ["CS101", "computer_science", "MT101","math"]

stages:
  - *auth_save_token

  - *create_studyfield_save_all

  - name: "When a request with a valid json body,
            PUT /studyfields/id returns 200 and a json body that matches request"
    request:
      url: "{tavern.env_vars.BASE_URL}/studyfields/{returned_id}"
      method: PUT
      headers:
        Authorization: "Bearer {returned_access_token}"
        Content-Type: "application/json"
      json:
        code: "{update_code}"
        name: "{update_name}"
    response:
      status_code: 200
      json:
        id: !int "{returned_id:d}"
        code: "{update_code}"
        name: "{update_name}"

  - name: "When request is made,
            GET /studyfields/id returns 200 and a json body that matches updated studyfield"
    request:
      url: "{tavern.env_vars.BASE_URL}/studyfields/{returned_id}"
      method: GET
      headers:
        Authorization: "Bearer {returned_access_token}"
    response:
      status_code: 200
      json:
        id: !int "{returned_id:d}"
        code: "{update_code}"
        name: "{update_name}"
    

finally:
  - *delete_studyfield

  - *delete_studyfield_check

---

test_name: When request without json body, PUT /studyfields/id returns 400

marks:
  - parametrize:
      key:
        - request_code
        - request_name
      vals:
        - ["CS101", "computer_science"]

stages:
  - *auth_save_token

  - *create_studyfield_save_id

  - name: "When request without json body, PUT /studyfields/id returns 400"
    request:
      url: "{tavern.env_vars.BASE_URL}/studyfields/{returned_id}"
      method: PUT
      headers:
        Authorization: "Bearer {returned_access_token}"
        Content-Type: "application/json"
    response:
      status_code: 400

finally:
  - *delete_studyfield

  - *delete_studyfield_check

---

test_name: When request with invalid security key header, PUT /studyfields/id returns 401

marks:
  - parametrize:
      key:
        - wrong_token
        - request_code
        - request_name
      vals:
        - [ "satsgag", "CS101", "computer_science"]

stages:
  - *auth_save_token

  - *create_studyfield_save_id

  - name: "When request with invalid security key header, PUT /studyfields returns 401"
    request:
      url: "{tavern.env_vars.BASE_URL}/studyfields/{returned_id}"
      method: PUT
      headers:
        Authorization: "Bearer {wrong_token}"
        Content-Type: "application/json"
      json:
        code: "{request_code}"
        name: "{request_name}"
    response:
      status_code: 401

finally:
  - *delete_studyfield

  - *delete_studyfield_check

---

test_name: When studyfield deleted, PUT /studyfields/id returns 404

marks:
  - parametrize:
      key:
        - request_code
        - request_name
      vals:
        - ["CS101", "computer_science"]

stages:
  - *auth_save_token

  - *create_studyfield_save_id

finally:
  - *delete_studyfield

  - name: "When studyfield deleted, PUT /studyfields/id returns 404"
    request:
      url: "{tavern.env_vars.BASE_URL}/studyfields/{returned_id}"
      method: PUT
      headers:
        Authorization: "Bearer {returned_access_token}"
        Content-Type: "application/json"
      json:
        name: "{request_name}"
    response:
      status_code: 404

---

test_name: When id from studyfield that not exist, PUT /studyfields/id returns 404

marks:
  - parametrize:
      key:
        - wrong_id
        - update_code
        - update_name
      vals:
        - [ -1, "CS101", "computer_science"]

stages:
  - *auth_save_token

  - name: "When id from studyfield that not exist, PUT /studyfields/id returns 404"
    request:
      url: "{tavern.env_vars.BASE_URL}/studyfields/{wrong_id}"
      method: PUT
      headers:
        Authorization: "Bearer {returned_access_token}"
        Content-Type: "application/json"
      json:
        code: "{update_code}"
        name: "{update_name}"
    response:
      status_code: 404

---

test_name: When request with wrong json body data, PUT /studyfields/id returns 422

marks:
  - parametrize:
      key:
        - request_code
        - wrong_request_code
        - request_name
        - wrong_request_name
      vals:
        - ["CS101", "", "computer_science", ""]

stages:
  - *auth_save_token

  - *create_studyfield_save_id

  - name: "When request with wrong json body data(code), PUT /studyfields/id returns 422"
    request:
      url: "{tavern.env_vars.BASE_URL}/studyfields/{returned_id}"
      method: PUT
      headers:
        Authorization: "Bearer {returned_access_token}"
        Content-Type: "application/json"
      json:
        code: "{wrong_request_code}"
        name: "{request_name}"
    response:
      status_code: 422

  - name: "When request with wrong json body data(name), PUT /studyfields/id returns 422"
    request:
      url: "{tavern.env_vars.BASE_URL}/studyfields/{returned_id}"
      method: PUT
      headers:
        Authorization: "Bearer {returned_access_token}"
        Content-Type: "application/json"
      json:
        code: "{request_code}"
        name: "{wrong_request_name}"
    response:
      status_code: 422

finally:
  - *delete_studyfield

  - *delete_studyfield_check

---

test_name: When study field exists, DELETE /studyfields/id returns 204

marks:
  - parametrize:
      key:
        - request_code
        - request_name
      vals:
        - [ "CS101","computer_science" ]

stages:
  - *auth_save_token

  - *create_studyfield_save_id

  - *delete_studyfield

finally:
  - *delete_studyfield_check

---

test_name: When request with invalid security key header, DELETE /studyfields/id returns 401

marks:
  - parametrize:
      key:
        - wrong_token
        - request_code
        - request_name
      vals:
        - [ "satsgag", "CS101","computer_science"]

stages:
  - *auth_save_token
  
  - *create_studyfield_save_id

  - name: "When request with invalid security key header, DELETE /studyfields/id returns 401"
    request:
      url: "{tavern.env_vars.BASE_URL}/studyfields/{returned_id}"
      method: DELETE
      headers:
        Authorization: "Bearer {wrong_token}"
    response:
      status_code: 401

finally:
  - *delete_studyfield

  - *delete_studyfield_check

---

test_name: When studyfield deleted, DELETE /studyfields/id returns 404

marks:
  - parametrize:
      key:
        - request_code
        - request_name
      vals:
        - ["CS101","computer_science"]

stages:
  - *auth_save_token

  - *create_studyfield_save_id

finally:
  - *delete_studyfield

  - name: "When studyfield not exists, DELETE /studyfields/id returns 404"
    request:
      url: "{tavern.env_vars.BASE_URL}/studyfields/{returned_id}"
      method: DELETE
      headers:
        Authorization: "Bearer {returned_access_token}"
    response:
      status_code: 404

---

test_name: When id from studyfield that not exist, DELETE /studyfields/id returns 404

marks:
  - parametrize:
      key:
        - wrong_id
      vals:
        - [ -1 ]

stages:
  - *auth_save_token

  - name: "When id from studyfield that not exist, DELETE /studyfields/id returns 404"
    request:
      url: "{tavern.env_vars.BASE_URL}/studyfields/{wrong_id}"
      method: DELETE
      headers:
        Authorization: "Bearer {returned_access_token}"
    response:
      status_code: 404